services:

  backend:
    container_name: niq-backend-${CONTAINER_SUFFIX}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      # [중요] 모델 파일을 이미지에 굽지 않고 로컬 폴더를 직접 연결 (빌드 속도 최적화)
      - ./storage/models:/app/storage/models
      # 데이터 보존을 위한 마운트
      - ./storage/user_data:/app/storage/user_data
      - ./storage/train_data:/app/storage/train_data
      - ./storage/documents:/app/storage/documents
      - ./storage/extracted_texts:/app/storage/extracted_texts
      - ./storage/val_data:/app/storage/val_data
      # [추가] config.yaml 실시간 반영을 위해 마운트
      - ./config.yaml:/app/config.yaml
    env_file:
      - .env
    environment:
      # 컨테이너 간 통신을 위한 호스트 설정
      - RDB_HOST=${RDB_HOST}
      - MILVUS_HOST=${MILVUS_HOST}
      - MINIO_HOST=${MILVUS_PORT}
      # [중요] DB 접속 포트는 내부 포트(5432) 사용
      - RDB_PORT=5432
    depends_on:
      - db
      - standalone
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
  # --- PostgreSQL 서비스 ---
  db:
    image: postgres:15
    container_name: pps-postgres-${CONTAINER_SUFFIX}
    restart: always
    environment:
      POSTGRES_USER: ${RDB_USER}
      POSTGRES_PASSWORD: ${RDB_PASSWORD}
      POSTGRES_DB: ${RDB_NAME}
    ports:
      - "${RDB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  # --- Milvus 서비스 (etcd, minio, standalone) --- 
  # 분산 처리에 최적화된 벡터 검색 엔진이기 때문에 복잡한 구조를 가짐
  # Milvus etcd : 메타데이터 저장소
  etcd:
    container_name: milvus-etcd-${CONTAINER_SUFFIX}
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/storage/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  # --- Milvus Minio : 데이터 저장소 ---
  minio:
    container_name: milvus-minio-${CONTAINER_SUFFIX}
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_CONSOLE_PORT}:9001"
      - "${MINIO_API_PORT}:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/storage/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Milvus standalone : 벡터 검색 로직을 처리
  standalone:
    container_name: milvus-standalone-${CONTAINER_SUFFIX}
    image: milvusdb/milvus:v2.5.5
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/storage/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "${MILVUS_PORT}:19530"
      - "${MILVUS_ADMIN_PORT}:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus-${CONTAINER_SUFFIX}

volumes:
  postgres_data:        # 2. 키 이름은 고정
    name: postgres_data_${CONTAINER_SUFFIX} # 3. 실제 볼륨 이름에 변수 적용